services:
  - type: web
    name: volida
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn volida.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: volida.settings
      - key: PYTHON_VERSION
        value: 3.11
